#!/bin/python3

import jdatetime

date = jdatetime.date.today().strftime("%Y/%m/%d")
day = jdatetime.date.today().strftime("%a")

result = ""
numbers_map = {
    "0": "۰",
    "1": "۱",
    "2": "۲",
    "3": "۳",
    "4": "۴",
    "5": "۵",
    "6": "۶",
    "7": "۷",
    "8": "۸",
    "9": "۹"
}
days_map = {
    "Sat": "شنبه",
    "Sun": "یک‌شنبه",
    "Mon": "دوشنبه",
    "Tue": "سه‌شنبه",
    "Wed": "چهارشنبه",
    "Thu": "پنج‌شنبه",
    "Fri": "جمعه"
}
        
for c in date:
    if c in numbers_map:
        result += numbers_map[c]
        pass
    else:
        result += c
        pass
    pass

day = days_map[day]

print(" {} {}".format(result, day))
