#!/bin/bash

set -x

modes="suspend\nhibernate\nreboot\nshutdown"
action=
dir=$(pwd)
user=$USER
show_menu=
get_var=
color=
image=

for param in $@; do
    case $get_var in
        action)
            case $param in
                menu)
                    show_menu=1
                    ;;
                *)
                    action=$param
                    ;;
            esac
            ;;
        user)
            user=$param
            ;;
        dir)
            dir=$param
            ;;
        color)
            color="--color $param"
            ;;
        image)
            image="--image $param"
            ;;
        *)
            ;;
    esac

    get_var=

    case $param in
        -a)
            get_var=action
            ;;
        --action)
            get_var=action
            ;;
        -u)
            get_var=user
            ;;
        --user)
            get_var=user
            ;;
        -d)
            get_var=dir
            ;;
        --dir)
            get_var=dir
            ;;
        -c)
            get_var=color
            ;;
        --color)
            get_var=color
            ;;
        -i)
            get_var=image
            ;;
        --image)
            get_var=image
            ;;
        *)
    esac
done

case $action in
    hibernate)
        sudo s2disk > /dev/zero
        sudo -u $user i3lock -t $color $image
        ;;
    suspend)
        sudo s2ram > /dev/zero
        sudo -u $user i3lock -t $color $image
        ;;
    reboot)
        sudo shutdown -r now
        ;;
    shutdown)
        sudo shutdown now
        ;;
    *)
        ;;
esac

case $BLOCK_BUTTON in
    1)
        show_menu=1
        ;;
    2)
        ;;
    3)
        ;;
    4)
        ;;
    5)
        ;;
    6)
        ;;
    7)
        ;;
    *)
        ;;
esac

if [[ -n $show_menu ]]; then
    selected=$(echo -e $modes | dmenu -i)

    if [[ -n $selected ]]; then
        #sudo ~/.config/i3/i3tools/power-mgm --dir ~/.config/i3/i3tools --user $user --action $selected
        sudo ~/.config/i3/i3tools/power-mgm --user $user --action $selected $color $image
    fi
fi

#echo "{\"dir\":\"$dir\",\"user\":\"$user\",\"action\":\"$action\",\"selected\":\"$selected\"}" > ~/power.log
