#!/bin/bash

#set -x

id=$(xinput list | grep -ioE "touchpad\s+id=[0-9]+" | cut -d'=' -f2)
enabled=$(xinput list-props $id | grep -iE "device enabled" | grep -oE "[0-9]$")

#enabled=$((1 - $enabled))

if [[ $enabled -eq 0 ]]; then
    xinput enable $id
else
    xinput disable $id
fi
